### ISSUE TITLE
Cannot start plugin on Android

### ISSUE THREAD

**Issue by drorgl** [samuele-cozzi/obsidian-marp-slides#161]
Hi,

I'm trying to use Marp Slides on Android Obsidian but it cannot start, here's the error:
```
app.js:1 Plugin failure: marp-slides TypeError: Cannot destructure property 'dirname' of 'require(...)' as it is undefined.
    at node_modules/postcss/lib/map-generator.js (plugin:marp-slides:6304:11)
    at __require (plugin:marp-slides:14:50)
    at node_modules/postcss/lib/lazy-result.js (plugin:marp-slides:8137:24)
    at __require (plugin:marp-slides:14:50)
    at node_modules/postcss/lib/postcss.js (plugin:marp-slides:8865:22)
    at __require (plugin:marp-slides:14:50)
    at node_modules/@marp-team/marpit/lib/helpers/inline_style.js (plugin:marp-slides:8956:43)
    at __require (plugin:marp-slides:14:50)
    at node_modules/@marp-team/marpit/lib/markdown/background_image/advanced.js (plugin:marp-slides:9077:48)
    at __require (plugin:marp-slides:14:50)
    at node_modules/@marp-team/marpit/lib/markdown/background_image.js (plugin:marp-slides:9376:44)
    at __require (plugin:marp-slides:14:50)
    at node_modules/@marp-team/marpit/lib/marpit.js (plugin:marp-slides:15865:52)
    at __require (plugin:marp-slides:14:50)
    at node_modules/@marp-team/marpit/lib/index.js (plugin:marp-slides:16203:42)
    at __require (plugin:marp-slides:14:50)
    at node_modules/@marp-team/marp-core/lib/marp.js (plugin:marp-slides:130112:13)
    at __require (plugin:marp-slides:14:50)
    at anonymous (plugin:marp-slides:437574:32)
    at e.<anonymous> (app.js:1:2028752)
    at app.js:1:237544
    at Object.next (app.js:1:237649)
    at a (app.js:1:236367)
```

Looking into the error, it seems that the culprit is https://github.com/postcss/postcss/blob/f9a9868eb3a591cd99d504ac57bf7ee77380856b/lib/map-generator.js#L4

Thank you!

**Comment by drorgl** [comment]
I've looked into it more thoroughly, I think it can be solved with some changes.
I'll appreciate a code review
[https://github.com/samuele-cozzi/obsidian-marp-slides/compare/main...drorgl:obsidian-marp-slides:main](https://github.com/samuele-cozzi/obsidian-marp-slides/compare/main...drorgl:obsidian-marp-slides:main)
